### ISSUE TITLE
Inventory hides everything in it when there is an item with enchantment in your hand

### ISSUE THREAD

**Issue by STRL1T** [HyperCol/AdvancedShader#4]
Greetings, you have a great mod! Could I ask you to correct a mistake related to enchanted items? Using shaders with your mod - regardless of which shaders, holding an enchanted apple, or a tool, and everything similar - my inventory disappears when I enter it. Once the enchantment is removed from the hand, items appear in the inventory, as well as icons. Many will be happy if this bug is fixed...

![image](https://user-images.githubusercontent.com/45147341/206911088-8761e22b-a7be-4699-abda-7e4e3f81ae8e.png)
![image](https://user-images.githubusercontent.com/45147341/206911103-17bf03bc-d072-478f-9f4c-525f6f02086f.png)

**Comment by ACGaming** [comment]
Can confirm this.
